import pyMeow as pm
import time
import os

# Debug logging setup
DEBUG_LOG_FILE = "offset_debug_log.txt"
GMOD_DEBUG_STATE_FILE = r"C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\data\lp_debug_dump.txt"

def debug_log(message):
    """Write debug message to log file"""
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    with open(DEBUG_LOG_FILE, "a", encoding="utf-8") as f:
        f.write(f"[{timestamp}] {message}\n")
    print(f"[DEBUG] {message}")

def clear_debug_log():
    """Clear the debug log file"""
    if os.path.exists(DEBUG_LOG_FILE):
        os.remove(DEBUG_LOG_FILE)
    debug_log("=== OFFSET DEBUG SESSION STARTED ===")

def log_gmod_state_file():
    """Append the in-game Lua debug dump if it exists"""
    debug_log("=== GMOD LUA STATE DUMP ===")

    if not os.path.exists(GMOD_DEBUG_STATE_FILE):
        debug_log(f"Lua state file not found: {GMOD_DEBUG_STATE_FILE}")
        debug_log("Run the HUD and use lp_debug_export_file once, or keep the HUD open for auto export.")
        return

    try:
        with open(GMOD_DEBUG_STATE_FILE, "r", encoding="utf-8", errors="ignore") as f:
            for raw_line in f:
                line = raw_line.rstrip("\r\n")
                if line:
                    debug_log(f"[LUA] {line}")
    except Exception as e:
        debug_log(f"Failed to read Lua state file: {str(e)}")

# Clear log at startup
clear_debug_log()

class Offsets:
    # Static offsets generated by our dumper.
    CLocalPlayer = 0x63CD54
    CClientEntityList = 0x9DB2C8
    ViewAngles = 0x65D764
    GlobalVars = 0x875E08
    PlayerResourceTable = 0x942E80

    # Useful netvars from the generated NetVars dump.
    m_iHealth = 0xD8
    m_iTeamNum = 0xE4
    m_vecOrigin = 0x438
    m_vecVelocity = 0x150
    m_angRotation = 0x444
    m_fFlags = 0x450
    m_CollisionGroup = 0x454
    m_hActiveWeapon = 0x2924
    m_hObserverTarget = 0x2C78
    m_hVehicle = 0x2CA0
    m_hUseEntity = 0x2CA8
    m_hOwnerEntity = 0x744
    Weapon_m_hOwner = 0x1BD8
    Weapon_m_iViewModelIndex = 0x1C00
    Weapon_m_iWorldModelIndex = 0x1C04
    Weapon_m_iState = 0x1C24
    Weapon_m_iClip1 = 0x1C38
    Weapon_m_iClip2 = 0x1C3C

def test_basic_connection():
    """Test if we can connect to gmod process"""
    debug_log("=== TESTING BASIC CONNECTION ===")
    
    if not pm.process_exists("gmod.exe"):
        debug_log("ERROR: gmod.exe process not found!")
        return False
    
    try:
        gmod_exe = pm.open_process("gmod.exe")
        debug_log("SUCCESS: Connected to gmod.exe process")
        return gmod_exe
    except Exception as e:
        debug_log(f"ERROR: Failed to open gmod.exe process: {str(e)}")
        return False

def test_modules(gmod_exe):
    """Test if we can find required DLL modules"""
    debug_log("=== TESTING DLL MODULES ===")
    
    modules = {}
    
    try:
        client_dll = pm.get_module(gmod_exe, "client.dll")
        debug_log(f"SUCCESS: Found client.dll at 0x{client_dll['base']:08X}")
        modules['client'] = client_dll
    except Exception as e:
        debug_log(f"ERROR: Failed to find client.dll: {str(e)}")
        return False
    
    try:
        engine_dll = pm.get_module(gmod_exe, "engine.dll")
        debug_log(f"SUCCESS: Found engine.dll at 0x{engine_dll['base']:08X}")
        modules['engine'] = engine_dll
    except Exception as e:
        debug_log(f"ERROR: Failed to find engine.dll: {str(e)}")
        return False
    
    try:
        materialsystem_dll = pm.get_module(gmod_exe, "materialsystem.dll")
        debug_log(f"SUCCESS: Found materialsystem.dll at 0x{materialsystem_dll['base']:08X}")
        modules['materialsystem'] = materialsystem_dll
    except Exception as e:
        debug_log(f"WARNING: Failed to find materialsystem.dll: {str(e)}")
    
    return modules

def test_offsets(gmod_exe, modules):
    """Test the static offsets produced by our dumper"""
    debug_log("=== TESTING GENERATED STATIC OFFSETS ===")
    
    results = {}
    
    # CLocalPlayer is an engine-side slot/index value, not a client entity pointer.
    try:
        local_player_index = pm.r_int(gmod_exe, modules['engine']['base'] + Offsets.CLocalPlayer)
        debug_log(f"CLocalPlayer slot test: {local_player_index}")
        results["CLocalPlayer"] = local_player_index >= 0
    except Exception as e:
        debug_log(f"CLocalPlayer offset failed: {str(e)}")
        results["CLocalPlayer"] = False

    # CClientEntityList is the resolved interface instance address.
    try:
        entity_list_interface = modules['client']['base'] + Offsets.CClientEntityList
        entity_list_vtable = pm.r_int64(gmod_exe, entity_list_interface)
        debug_log(f"CClientEntityList instance: 0x{entity_list_interface:016X}")
        debug_log(f"CClientEntityList vtable: 0x{entity_list_vtable:016X}")
        results["CClientEntityList"] = entity_list_vtable != 0
    except Exception as e:
        debug_log(f"CClientEntityList offset failed: {str(e)}")
        results["CClientEntityList"] = False

    # ViewAngles points to a 3-float angle vector on engine.dll.
    try:
        view_angles = pm.r_vec3(gmod_exe, modules['engine']['base'] + Offsets.ViewAngles)
        debug_log(f"ViewAngles test: {view_angles}")
        results["ViewAngles"] = True
    except Exception as e:
        debug_log(f"ViewAngles offset failed: {str(e)}")
        results["ViewAngles"] = False

    # GlobalVars is a pointer slot inside client.dll.
    try:
        global_vars_ptr = pm.r_int64(gmod_exe, modules['client']['base'] + Offsets.GlobalVars)
        debug_log(f"GlobalVars pointer test: 0x{global_vars_ptr:016X}")
        results["GlobalVars"] = global_vars_ptr != 0
    except Exception as e:
        debug_log(f"GlobalVars offset failed: {str(e)}")
        results["GlobalVars"] = False

    # PlayerResourceTable is a recv table metadata address in client.dll.
    try:
        player_resource_table = modules['client']['base'] + Offsets.PlayerResourceTable
        debug_log(f"PlayerResourceTable address test: 0x{player_resource_table:016X}")
        results["PlayerResourceTable"] = player_resource_table != 0
    except Exception as e:
        debug_log(f"PlayerResourceTable offset failed: {str(e)}")
        results["PlayerResourceTable"] = False

    return results

def log_generated_reference():
    """Log the generated offsets/netvars we currently trust"""
    debug_log("=== GENERATED REFERENCE VALUES ===")
    debug_log(f"CLocalPlayer = 0x{Offsets.CLocalPlayer:08X} (engine.dll)")
    debug_log(f"CClientEntityList = 0x{Offsets.CClientEntityList:08X} (client.dll)")
    debug_log(f"ViewAngles = 0x{Offsets.ViewAngles:08X} (engine.dll)")
    debug_log(f"GlobalVars = 0x{Offsets.GlobalVars:08X} (client.dll)")
    debug_log(f"PlayerResourceTable = 0x{Offsets.PlayerResourceTable:08X} (client.dll)")
    debug_log(f"m_iHealth = 0x{Offsets.m_iHealth:08X}")
    debug_log(f"m_iTeamNum = 0x{Offsets.m_iTeamNum:08X}")
    debug_log(f"m_vecOrigin = 0x{Offsets.m_vecOrigin:08X}")
    debug_log(f"m_vecVelocity = 0x{Offsets.m_vecVelocity:08X}")
    debug_log(f"m_angRotation = 0x{Offsets.m_angRotation:08X}")
    debug_log(f"m_fFlags = 0x{Offsets.m_fFlags:08X}")
    debug_log(f"m_CollisionGroup = 0x{Offsets.m_CollisionGroup:08X}")
    debug_log(f"m_hActiveWeapon = 0x{Offsets.m_hActiveWeapon:08X}")
    debug_log(f"m_hObserverTarget = 0x{Offsets.m_hObserverTarget:08X}")
    debug_log(f"m_hVehicle = 0x{Offsets.m_hVehicle:08X}")
    debug_log(f"m_hUseEntity = 0x{Offsets.m_hUseEntity:08X}")
    debug_log(f"m_hOwnerEntity = 0x{Offsets.m_hOwnerEntity:08X}")
    debug_log(f"Weapon_m_hOwner = 0x{Offsets.Weapon_m_hOwner:08X}")
    debug_log(f"Weapon_m_iViewModelIndex = 0x{Offsets.Weapon_m_iViewModelIndex:08X}")
    debug_log(f"Weapon_m_iWorldModelIndex = 0x{Offsets.Weapon_m_iWorldModelIndex:08X}")
    debug_log(f"Weapon_m_iState = 0x{Offsets.Weapon_m_iState:08X}")
    debug_log(f"Weapon_m_iClip1 = 0x{Offsets.Weapon_m_iClip1:08X}")
    debug_log(f"Weapon_m_iClip2 = 0x{Offsets.Weapon_m_iClip2:08X}")

def main():
    debug_log("Starting offset debug test...")
    
    # Test basic connection
    gmod_exe = test_basic_connection()
    if not gmod_exe:
        debug_log("CRITICAL: Cannot connect to gmod.exe. Make sure the game is running.")
        return
    
    # Test modules
    modules = test_modules(gmod_exe)
    if not modules:
        debug_log("CRITICAL: Cannot find required DLL modules.")
        return
    
    # Test offsets
    offset_results = test_offsets(gmod_exe, modules)
    
    # Log the generated reference values so they are visible in one place.
    log_generated_reference()
    log_gmod_state_file()
    
    # Summary
    debug_log("=== SUMMARY ===")
    working_offsets = sum(offset_results.values())
    total_offsets = len(offset_results)
    debug_log(f"Working offsets: {working_offsets}/{total_offsets}")
    
    for offset_name, working in offset_results.items():
        status = "WORKING" if working else "FAILED"
        debug_log(f"  {offset_name}: {status}")
    
    debug_log("=== DEBUG COMPLETE ===")
    debug_log("Check debug_log.txt for detailed information")

if __name__ == "__main__":
    main() 
